[package]
name = "day07"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
cargo-manifest = "0.17.0"
chrono = "0.4.38"
reqwest = { version = "0.12.9", features = ["blocking"] }
